# Site settings
title: ESA Cup 2016
email: Luca.Del.Monte@esa.int

description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://esacup2016.github.io" # the base hostname & protocol for your site
twitter_username:
github_username:

# include: "_pages/"

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
